#cloud-config
bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

ssh_authorized_keys:
  - ${public_key_openssh}

runcmd:
  - setenforce 0
  - sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config