- name: Create spark group
  group: 
    name: spark
    system: true
    state: present

- name: Create spark user
  user: 
    name: spark
    group: spark
    system: true
    shell: /sbin/nologin
    home: /opt/spark
    create_home: false
    state: present

- name: Create spark install directory
  file: 
    path: /opt/spark
    state: directory
    owner: spark
    group: spark
    mode: "0755"

- name: Download spark
  get_url:
    url: "https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz"
    dest: /tmp/spark-3.5.1-bin-hadoop3.tgz
    mode: "0644"
    force: false

- name: Extract spark
  unarchive: 
    src: /tmp/spark-3.5.1-bin-hadoop3.tgz
    dest: /opt/spark
    remote_src: true
    extra_opts: ["--strip-components=1"]
    creates: /opt/spark/bin/spark-submit
    owner: spark
    group: spark

- name: Create spark directories
  file:
    path: "{{ item }}"
    state: directory
    owner: spark
    group: spark
    mode: "0755"
  loop:
    - /opt/spark/logs
    - /opt/spark/pids

- name: Create spark event directory
  file:
    path: /data/nyc-taxi/spark-events
    state: directory
    owner: spark
    group: spark
    mode: "0755"

- name: Deploy spark-env.sh
  template:
    src: spark-env.sh.j2
    dest: /opt/spark/conf/spark-env.sh
    owner: spark
    group: spark
    mode: "0755"
  notify: Restart spark master

- name: Deploy spark workers
  template:
    src: workers.j2
    dest: /opt/spark/conf/workers
    owner: spark
    group: spark
    mode: "0644"
  notify: Restart spark master

- name: Install spark-master systemd
  template:
    src: spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service
    mode: "0644"
  notify: Restart spark master

- name: Enable and start spark master
  systemd:
    name: spark-master
    state: started
    enabled: true
    daemon_reload: true

- name: Set permission on spark pipeline directory
  file:
    path: "{{ project_dir }}/spark"
    state: directory
    mode: "0755"
    recurse: true

- name: Make almalinux home directory accessible to spark user
  file:
    path: /home/almalinux
    state: directory
    mode: "0755"