- name: Create data directory
  file:
    path: /data
    state: directory
    owner: almalinux
    group: almalinux
    mode: "0755"

- name: Create nfs directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /data, owner: almalinux, group: almalinux, mode: "0755" }
    - { path: /data/nyc-taxi, owner: spark, group: spark, mode: "0755" }
    - { path: /data/nyc-taxi/raw, owner: spark, group: spark, mode: "0755" }
    - { path: /data/nyc-taxi/model, owner: spark, group: spark, mode: "0755" }
    - { path: /data/nyc-taxi/cleaned, owner: spark, group: spark, mode: "0755" }
    - { path: /data/nyc-taxi/spark-events, owner: spark, group: spark, mode: "0755" }
    - { path: /data/nyc-taxi/outputs, owner: spark, group: spark, mode: "0777" }

- name: Configure exports
  template:
    src: exports.j2
    dest: /etc/exports
  notify: Reload NFS exports

- name: Enable and start NFS server
  service: 
    name: nfs-server
    state: started
    enabled: true
    